framework:
    rate_limiter:
        download_limiter:
            policy: 'token_bucket'
            limit: 10
            interval: '60 seconds'
        
        upload_limiter:
            policy: 'token_bucket'
            limit: 5
            interval: '60 seconds'
        
        login_limiter:
            policy: 'fixed_window'
            limit: 5
            interval: '15 minutes'
